### ISSUE TITLE
Residential whole home deep clean pricing 

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/community-content#12]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

**Comment by cassiclean** [comment]
Id like to write on this topic

Outline:
Do's and Dont's section
Protect you profits section
Hourly rate vs Flat rate in residential

**Comment by cassiclean** [comment]
Article wrote, submitted and invoice sent! @SamHoffer
