### ISSUE TITLE
Clearing odors 

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/community-content#15]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

**Comment by Mr254Kenya** [comment]
Hello, @SamHoffer hope you are alright? I request an opportunity to handle this issue/task.  Attached is the general outline of how I plan to approach the task. Thanks
[General Article Outline_ Clearing odors #15.docx](https://github.com/Taskbird/community-content/files/7711529/General.Article.Outline_.Clearing.odors.15.docx)

**Comment by SamHoffer** [comment]
@Mr254Kenya I like your outline. Something that is usually up for discussion when focusing on odors and how to cover them up, is the type of product that is used or the ingredients used in certain products. This is brought up for many reasons such as, allergies and client preferences. If you can include a way to clear odors for allergy and scent sensitive clients that would be great! Otherwise, happy writing!
