### ISSUE TITLE
Deep cleaning electronics 

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/community-content#17]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

**Comment by Mr254Kenya** [comment]
Hello @SamHoffer, I request the opportunity to tackle this issue. Attached is the general outline of how I plan to approach the task. Regards
[Deep cleaning electronics #17.docx](https://github.com/Taskbird/community-content/files/7711703/Deep.cleaning.electronics.17.docx)

**Comment by SamHoffer** [comment]
@Mr254Kenya Your outline looks good but if you could include a "common mistake" area and what to avoid when cleaning your electronics. Also include a way that people can better locate businesses that specialize in computer care( if not possible no worries).
