### ISSUE TITLE
Kitchen cleaning

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/community-content#18]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic! 

When you submit your final draft send your file to community@taskbird.com

**Comment by ninjaclean** [comment]
Hi, I'd like to create a blog article for this topic.

**Comment by SamHoffer** [comment]
@ninjaclean Thank you for taking this topic, we are excited to see the article you produce for this. Make sure to stick to the [blog guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf) listed above. When you complete you outline please share it with us here or send to the email community@taskbird.com.

**Comment by ebolton3** [comment]
If this topic is still open, I'd like to create a blog article for this topic

**Comment by SamHoffer** [comment]
@ninjaclean Are you still available to write for this topic? Please respond promptly as we do have other community members who are interested in this issue.

**Comment by SamHoffer** [comment]
@ebolton3 I will notify you when we can confirm that this piece has not been taken by another community member. Thank you for your understanding. If there is another topic that you are interested in please let me know.

**Comment by ninjaclean** [comment]
Hi, yes Sam Hoffer, I will have the outline to you by tomorrow. The outline for bathroom cleaning will be sent to you today. Assuming the outlines are good, I can have both completed by Monday. Please let me know if that works for you.
Thanks, Ninjaclean

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by SamHoffer** [comment]
@ninjaclean Yes, this works for me. Glad to hear the pieces are coming along well, I'll review the outlines upon their arrival and will notify you of any changes that should be made.

**Comment by SamHoffer** [comment]
@ebolton3 It appears that our user who previously chose this topic is no longer able to complete it. If you still want to write about this topic please let me know.

**Comment by cassiclean** [comment]
@SamHoffer id like to tackle this if there’s no one else on it

**Comment by cassiclean** [comment]
Is this topic still available to be written? I have

**Comment by SamHoffer** [comment]
@cassiclean Yes it is, please go ahead and share your outline for this topic.

**Comment by cassiclean** [comment]
@SamHoffer Article has been emailed on this issue

**Comment by SamHoffer** [comment]
@cassiclean Thank you for submitting your article, payment should be completed to you sortly. Please let me know when you have received it!

**Comment by cassiclean** [comment]
Will do! I am finishing up my post cleaning article as we speak
