### ISSUE TITLE
Building long-term client relationships

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/community-content#2]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

**Comment by GageMcClark** [comment]
I would like to write for this topic. I have experience as a small business owner and I think it would be a great fit!

**Comment by GageMcClark** [comment]
Here is my outline if this topic is still available. Thank you! 
[Outline TOPIC #2](https://github.com/Taskbird/community-content/files/7592605/Topic.2.docx)

**Comment by GageMcClark** [comment]
Thank you @GageMcClark for your outline, I will approve you to write an article for this topic. However, I do request that you include how this topic can directly effect a cleaning company specifically.

**Comment by SamHoffer** [comment]
Thank you @GageMcClark for your outline, I will approve you to write an article for this topic. However, I do request that you include how this topic can directly effect a cleaning company specifically.
