### ISSUE TITLE
Oven cleaning

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/community-content#22]
### Safe and effective ways to clean ovens and stove tops. 

Comment if you want to create content for this topic.

**Comment by testclean52** [comment]
I want to write a blog article about this topic!

**Comment by SamHoffer** [comment]
Thank you for your interest @testclean52. Please submit your outline to the comment section to be reviewed by our admin.

**Comment by testclean52** [comment]
[BUS 345(SIS SH).docx](https://github.com/Taskbird/community-content/files/7213620/BUS.345.SIS.SH.docx)

Here is my outline

**Comment by SamHoffer** [comment]
Thank you for uploading you outline. Everything looks good, please refer to the blog outline link in the topic for any questions about structure or length.
