### ISSUE TITLE
Writing a blog for Taskbird in Github

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/community-content#24]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/main/Blog%20Guidlines.pdf)

Comment bellow if you want to create a blog article or a video for this topic! 

When you submit your final draft send your file to community@taskbird.com

**Comment by kaylabis** [comment]
Hi @testclean52, thanks for tackling this topic! Please submit your outline to this comment section once you're finished. Once received, we'll approve your outline and you can get started writing your final draft.

**Comment by testclean52** [comment]
Okay thank you. I will submit it as soon as I have finished writing the outline.

**Comment by testclean52** [comment]
Here is my blog outline! @kaylabis 
[BLOGOUTLINE.docx](https://github.com/Taskbird/community-content/files/7263649/BLOGOUTLINE.docx)

**Comment by kaylabis** [comment]
Hi @testclean52 , your outline has been approved. You may now begin writing your final draft. Please refer to the blog guidelines for formatting and submitting your final draft.

**Comment by testclean52** [comment]
Okay, I will do that. Thank for approving it @kaylabis.
