### ISSUE TITLE
Hardwood floor cleaning

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/community-content#25]
Hardwood floors can be delicate cleaning projects and can be difficult to maintain over time. How can hardwood floors be kept shining? 

Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

When you submit your final draft send your file to community@taskbird.com

**Comment by Mr254Kenya** [comment]
Hello Sam, would like the opportunity to create a blog article for the topic. Here are a few of my samples, for other clients. Thanks
[The Ultimate List of Moving Supplies.docx](https://github.com/Taskbird/community-content/files/7520655/The.Ultimate.List.of.Moving.Supplies.docx)
[7 Tips to Manage Stress and Anxiety as a Remote Worker.docx](https://github.com/Taskbird/community-content/files/7520659/7.Tips.to.Manage.Stress.and.Anxiety.as.a.Remote.Worker.docx)

**Comment by Mr254Kenya** [comment]
[BLOG OUTLINE_ Hardwood floor cleaning #25 (2).docx](https://github.com/Taskbird/community-content/files/7521040/BLOG.OUTLINE_.Hardwood.floor.cleaning.25.2.docx)

**Comment by SamHoffer** [comment]
Hi @Mr254Kenya , I really like the outline you've made for this topic. Go ahead and complete the topic with a minimum of 1,000 words and submit it to community@taskbird.com. Reach out with any further questions!

**Comment by Mr254Kenya** [comment]
> Hi @Mr254Kenya , I really like the outline you've made for this topic. Go ahead and complete the topic with a minimum of 1,000 words and submit it to [community@taskbird.com](mailto:community@taskbird.com). Reach out with any further questions!

Thanks, I'm on it

**Comment by Mr254Kenya** [comment]
Hello Sam Hoffer

Can you please avail to me the website for internal linking

**Comment by SamHoffer** [comment]
Hello @Mr254Kenya the website is Taskbird.com.

**Comment by Mr254Kenya** [comment]
Okay . Had already sent the document but let me do internal backlinking and
then I resend it immediately
