### ISSUE TITLE
Post construction cleaning

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/community-content#26]
After a construction project there are a lot of steps that should be taken to clean up the area. 

Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

When you submit your final draft send your file to community@taskbird.com

**Comment by Mr254Kenya** [comment]
@SamHoffer Hope you are doing great? I register my interest to handle this particular issue. Attached is a general outline of how I plan to approach the content. Regard
[General Task Outline_ Post construction cleaning #26.docx](https://github.com/Taskbird/community-content/files/7655384/General.Task.Outline_.Post.construction.cleaning.26.docx)
s

**Comment by SamHoffer** [comment]
@Mr254Kenya Thank you for your interest in this topic. After reviewing your outline I think it's a great start to this article. Please submit your final piece to the community email.

**Comment by Mr254Kenya** [comment]
Okay, will do so as soon as possible.
