### ISSUE TITLE
What is deep cleaning? 

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/community-content#27]
How often, what to charge, proper methods? 
Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

When you submit your final draft send your file to community@taskbird.com

**Comment by cassiclean** [comment]
id like to write on this topic

**Comment by SamHoffer** [comment]
@cassiclean great! Please submit an outline of your article to this comment section before beginning your final piece.

**Comment by cassiclean** [comment]
I will cover:
      how often to deep clean:
-a residential
-a STR
-homes with pets
      pricing of a deep clean and why to charge this way
-how tp pay help on deep clean
what does a deep clean truly consist of
final touches that clients appreciate
selling points of more frequent deep cleanings

**Comment by cassiclean** [comment]
@SamHoffer is that outline sufficient? I'm new to this and I just want to do a good job so please tell me any improvements I need to make.

**Comment by cassiclean** [comment]
@SamHoffer  I am almost finished with this article

**Comment by SamHoffer** [comment]
@cassiclean Looking forward to the final piece!

**Comment by cassiclean** [comment]
I have submitted this final piece

**Comment by SamHoffer** [comment]
@cassiclean received!
