### ISSUE TITLE
How to find clients and generate valuable leads

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/community-content#28]
Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

When you submit your final draft send your file to community@taskbird.com

**Comment by cassiclean** [comment]
Id like to write on this topic
@SamHoffer 

Outline:
Finding clients from word of mouth
creating value to your name
Using online platforms to find work
Hands on interactions create the best leads
keeping clients happy

**Comment by cassiclean** [comment]
Article on Finding clients complete and emailed.
