### ISSUE TITLE
Neighborhood Snow Plowing Business

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/community-content#29]
The winter season upon us, how can you capitalize? 
Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

When you submit your final draft send your file to community@taskbird.com

**Comment by GageMcClark** [comment]
I think I have a good idea for this topic. How to start a small business is what I was going to use for the outline.

**Comment by SamHoffer** [comment]
@GageMcClark Yes, anything along those lines works, if you are in a snowy area and are comfortable making a video about this topic that would be great! If not you can submit you outline whenever you are ready.

**Comment by GageMcClark** [comment]
@SamHoffer I am in a snowy area but there unfortunately is enough snow fall for a snow plowing video quite yet. I will submit  a written article but I am open to a video.

**Comment by GageMcClark** [comment]
[Snow plowing.docx](https://github.com/Taskbird/community-content/files/7652588/Snow.plowing.docx)
This is my outline for the snow plowing.

**Comment by SamHoffer** [comment]
@GageMcClark just read it over, everything looks really good. If you can include product recommendations that would be perfect. Something for the shovel, snow plow, and salt. Possibly describe the business info that should be handed out to the customers(business card?) Otherwise you are free to create the final draft of this topic.
