### ISSUE TITLE
Marketing for your cleaning business

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/community-content#31]
Digital, word of mouth, traditional marketing, etc. What are the best ways to advertise a cleaning business? 

Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

When you submit your final draft send your file to community@taskbird.com

**Comment by GageMcClark** [comment]
I would like to write about this. I have experience in starting a company and helping existing gain more customers.

**Comment by SamHoffer** [comment]
@GageMcClark When you have an outline ready please send it to me or the community@taskbird.com email. Thank you and looking forward to reading this.

**Comment by GageMcClark** [comment]
I have sent in my final draft, let me know if there are any changes I can make. The last article that I wrote was about using snow plowing as a marketing tool. I was thinking it would be a good link in this article but I don't see it posted in Taskbird website. thanks @SamHoffer

**Comment by SamHoffer** [comment]
@GageMcClark  everything looks great, thank you for sending your invoice too. I will see what we can do as far as back linking the articles that you have written. Thanks for the suggestion. 
Please notify me when you have received payment.
