### ISSUE TITLE
Insurance plans for a cleaning company owner 

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/community-content#4]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

**Comment by kaylabis** [comment]
Here's my outline for this topi
[Outline for blog.docx](https://github.com/Taskbird/community-content/files/7247270/Outline.for.blog.docx)
c:

**Comment by SamHoffer** [comment]
Thank you submitting your outline @kaylabis we will get back to you with any comments after we have reviewed your work.

**Comment by Mr254Kenya** [comment]
Hello, @SamHoffer I'm requesting the opportunity to handle this particular issue. Attached is a general outline of how I plan to approach the web post.

[Blog Article Outline_ Insurance plans for a cleaning company owner #4.docx](https://github.com/Taskbird/community-content/files/7617179/Blog.Article.Outline_.Insurance.plans.for.a.cleaning.company.owner.4.docx)
.

**Comment by SamHoffer** [comment]
@Mr254Kenya, your outline looks good. I ask that you include popular insurance companies that cleaning companies currently use and why those are good/bad choices. Otherwise, we are looking forward to reading more about this topic.

**Comment by Mr254Kenya** [comment]
Hello, Sam, thanks for the reply.

Okay, will try my best to include the information requested.

Regards
