### ISSUE TITLE
Hiring new employees 

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/community-content#9]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Community vote
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by cassiclean** [comment]
I would like to write this one

**Comment by SamHoffer** [comment]
Hello @cassiclean , I believe another community member has asked to write about this but if they do not respond soon I will approve you for this article.

**Comment by SamHoffer** [comment]
@cassiclean sounds good, please include a detailed outline of this topic. We are looking for this article to be very in depth and over 1,000 words.

**Comment by cassiclean** [comment]
@SamHoffer I will email an outline tomorrow

**Comment by cassiclean** [comment]
@SamHoffer outline has been sent

**Comment by SamHoffer** [comment]
@cassiclean Thank you, a response has been sent to you.
